from logging import getLogger

from alembic.command import check, revision, upgrade, stamp
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected

if __name__ == "__main__":
    logger = getLogger(name="migrations.env")
    alembic_config = Config("alembic.ini")

    def create_and_update():
        try:
            check(config=alembic_config)
        except AutogenerateDiffsDetected:
            revision(config=alembic_config, autogenerate=True)
            upgrade(config=alembic_config, revision="head")

    try:
        create_and_update()
    except Exception as ex:
        logger.error(ex)
        stamp(config=alembic_config, revision="head")
        create_and_update()
